theme: jekyll-theme-slate
title: A Distributed Implementation of the Quantum Fourier Transformation in Qiskit and QNE-ADK
description: RIPE Quantum Internet Hackathon 2022
author: Bruno Rijsman
plugins:
    - jekyll-seo-tag
google_analytics: UA-31532124-6
