name: All checks

on: push

jobs:
    checks:
        name: Run all checks
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - uses: actions/setup-python@master
              with:
                  python-version: 3.8
            - uses: py-actions/py-dependency-install@v4
              with:
                  path: 'minimal-requirements.txt'
            - run: scripts/all_checks.sh
